export enum EntityType {
  PERSON = 'PERSON',
  INSTITUTION = 'INSTITUTION',
  SIGHT = 'SIGHT',
  SETTLEMENT = 'SETTLEMENT',
  CREATION = 'CREATION',
  PROTAG_CREATION = 'PROTAG_CREATION',
}

export type EditorDateType = 'when' | 'when-custom' | 'notAfter' | 'notBefore' | 'from-to' | 'notBefore-notAfter';
export type DateCertainty = 'high' | 'medium' | 'low';
export type LetterState = {
  viewMode: 'CODE' | 'WYSIWYG' | null;
  xmlContent: string | null;
};

export type HeaderPerson = {
  name: string;
  key: string;
};

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const languageMap = {
  de: 'Deutsch',
  en: 'Englisch',
  fr: 'Französisch',
  it: 'Italienisch',
  span: 'Spanisch',
  la: 'Latein',
  grc: 'Altgriechisch',
  yi: 'Jiddisch',
} as const;

export type LanguageOption = {
  [K in keyof typeof languageMap]: { value: K; label: (typeof languageMap)[K] };
}[keyof typeof languageMap];

const languages: LanguageOption[] = [
  { value: 'de', label: 'Deutsch' },
  { value: 'en', label: 'Englisch' },
  { value: 'fr', label: 'Französisch' },
  { value: 'it', label: 'Italienisch' },
  { value: 'span', label: 'Spanisch' },
  { value: 'la', label: 'Latein' },
  { value: 'grc', label: 'Altgriechisch' },
  { value: 'yi', label: 'Jiddisch' },
];

export type MenuAction = ({ node }: { node?: Node }) => Promise<void>;

export interface MenuItem {
  identifier: string;
  label: string;
  type?: 'inactive';
  action?: MenuAction;
}

export type ContentAddrLine = {
  hasHighlight: boolean;
  content: string;
  rendType: string | null;
};

export const validParagraphClasses = ['PARAGRAPH_LEFT', 'PARAGRAPH_RIGHT', 'PARAGRAPH_CENTER'] as const;

export type ParagraphClass = (typeof validParagraphClasses)[number];

export type ContentAddressEntry = {
  isNewEntry: boolean;
  deleteAddress: boolean;
  type: 'SENDER' | 'RECIPIENT';
  hasHead: boolean;
  hasParagraph: boolean;
  paragraph: ParagraphClass | null;
  addrLines: ContentAddrLine[];
};

const dialogTypes = {
  EDIT_LANGUAGES: 'EDIT_LANGUAGES',
  ADD_FOOTNOTE_AUTHOR: 'ADD_FOOTNOTE_AUTHOR',
  ADD_GREETINGS_FORMULA: 'ADD_GREETINGS_FORMULA',
  ADD_LETTER_TO_PROTAG: 'ADD_LETTER_TO_PROTAG',
  ADD_LETTER_FROM_PROTAG: 'ADD_LETTER_FROM_PROTAG',
  ADD_NEW_LETTER: 'ADD_NEW_LETTER',
  ADD_NOTE: 'ADD_NOTE',
  ADD_TEI_HEADER: 'ADD_TEI_HEADER',
  ADD_WRITING_PART: 'ADD_WRITING_PART',
  ATTACHMENT_ADD: 'ATTACHMENT_ADD',
  DATE_FROM_TO_ADD: 'DATE_FROM_TO_ADD',
  DATE_NOT_BEFORE_AFTER_ADD: 'DATE_NOT_BEFORE_AFTER_ADD',
  DATE_NOT_AFTER_ADD: 'DATE_NOT_AFTER_ADD',
  DATE_NOT_BEFORE_ADD: 'DATE_NOT_BEFORE_ADD',
  DATE_WHEN_ADD: 'DATE_WHEN_ADD',
  DATE_WHEN_CUSTOM_ADD: 'DATE_WHEN_CUSTOM_ADD',
  EDIT_NOTE: 'EDIT_NOTE',
  MANAGE_ADDRESS_RECIPIENT: 'MANAGE_ADDRESS_RECIPIENT',
  MANAGE_ADDRESS_SENDER: 'MANAGE_ADDRESS_SENDER',
  MANAGE_GREETINGS_FORMULA: 'MANAGE_GREETINGS_FORMULA',
  MANAGE_HEADER_AUTHOR_WRITER: 'MANAGE_HEADER_AUTHOR_WRITER',
  MANAGE_HEADER_RECEIVER: 'MANAGE_HEADER_RECEIVER',
  MANAGE_WRITING_ACT_AUTHOR_WRITER: 'MANAGE_WRITING_ACT_AUTHOR_WRITER',
  PUBLISH_LETTER: 'PUBLISH_LETTER',
  RESET_LETTER: 'RESET_LETTER',
  SOURCE_DESC_HANDWRITING: 'SOURCE_DESC_HANDWRITING',
};

export type TmpIdPrefix = (typeof EditorConstants.tmpIdPrefixes)[keyof typeof EditorConstants.tmpIdPrefixes];

export const EditorConstants = {
  ALLOWED_PARENT_TAG: "div[type='act_of_writing']",
  FORBIDDEN_PARENT_TAG: 'teiheader',
  RESTRICTED_TAGS: ['persname', 'placename', 'date', 'hi'],
  ENTITY_TYPES: EntityType,
  LANGUAGES: languages,

  tmpIdPrefixes: {
    MANAGE_GREETINGS_FORMULA: dialogTypes.MANAGE_GREETINGS_FORMULA,
    ADD_GREETINGS_FORMULA: dialogTypes.ADD_GREETINGS_FORMULA,
  },
  compMappingLeft: {
    SEARCH: 'SEARCH',
    FAVOURITES: 'FAVOURITES',
  },
  compMappingRight: {
    USER_ACTIONS: 'USER_ACTIONS',
    ASSIGNED: 'ASSIGNED',
    SET_FAVOURITE: 'SET_FAVOURITE',
    PUBLISH_LETTER: 'PUBLISH_LETTER',
    ENT_PERSON: 'ENT_PERSON',
    ENT_PLACE: 'ENT_PLACE',
    ENT_LETTER: 'ENT_LETTER',
    ENT_CREATION: 'ENT_CREATION',
    ENT_FMBC_CREATION: 'ENT_FMBC_CREATION',
    ADD_SPECIAL_ANNOTATION: 'ADD_SPECIAL_ANNOTATION',
  },
  dialogTypes,
  AUTOCOMPLETE_INPUT_CHANGE_REASONS: {
    INPUT: 'input',
    RESET: 'reset',
    CLEAR: 'clear',
    BLUR: 'BLUR',
    SELECT_OPTION: 'selectOption',
    REMOVE_OPTION: 'removeOption',
  },

  changeTypes: {
    NODE_REMOVED: 'NODE_REMOVED',
    MANUAL_CODE_CHANGE: 'MANUAL_CODE_CHANGE',
    person: {
      ADDED: 'PERSON_ADDED',
      REMOVED: 'PERSON_REMOVED',
    },
    note: {
      ADDED: 'NOTE_ADDED',
      CONTENT_CHANGED: 'NOTE_CONTENT_CHANGED',
      REMOVED: 'NOTE_REMOVED',
      TYPE_CHANGED: 'NOTE_TYPE_CHANGED',
    },
    date: {
      WHEN_ADDED: 'DATE_WHEN_ADDED',
      WHEN_MODIFIED: 'DATE_WHEN_MODIFIED',
    },
    place: {
      ADDED: 'PLACE_ADDED',
      REMOVED: 'PLACE_REMOVED',
    },
    creation: {
      ADDED: 'CREATION_ADDED',
      REMOVED: 'CREATION_REMOVED',
    },
    protag_creation: {
      ADDED: 'PROTAG_CREATION_ADDED',
      REMOVED: 'PROTAG_CREATION_REMOVED',
    },
    writing_act: {
      MANAGE_AUTHORS_WRITERS: 'ACT_OF_WRITING_MANAGE_AUTHORS_WRITERS',
      CHANGED_ORDER: 'ACT_OF_WRITING_CHANGED_ORDER',
    },
    misc: {
      ACT_OF_WRITING_ADDED: 'ACT_OF_WRITING_ADDED',
      ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
      BODY_ADDRESS_SENDER_CHANGED: 'BODY_ADDRESS_SENDER_CHANGED',
      BODY_ADDRESS_RECEIVER_CHANGED: 'BODY_ADDRESS_RECEIVER_CHANGED',
      BODY_ANNOTATION_REMOVED: 'BODY_ANNOTATION_REMOVED',
      BODY_PAGEBREAK_ADDED: 'BODY_PAGEBREAK_ADDED',
      BODY_SALUTE_ADDED: 'BODY_SALUTE_ADDED',
      BODY_SALUTE_REMOVED: 'BODY_SALUTE_REMOVED',
      BODY_SALUTE_CHANGED: 'BODY_SALUTE_CHANGED',
      CONTENT_FORMAT_CHANGED: 'CONTENT_FORMAT_CHANGED',
      DATE_ADDED: 'DATE_ADDED',
      DATE_REMOVED: 'DATE_REMOVED',
      GB_LETTER_ADDED: 'GB_LETTER_ADDED',
      HEADER_LANGUAGES_UPDATED: 'HEADER_LANGUAGES_UPDATED',
      HEADER_UPDATED: 'HEADER_UPDATED',
      PROTAG_LETTER_ADDED: 'PROTAG_LETTER_ADDED',
    },
  },
  attachmentTypeItems: [
    { value: 'certificate', label: 'Zeugnis' },
    { value: 'letter', label: 'Brief' },
    { value: 'letter_of_recommendation', label: 'Empfehlungsschreiben' },
    { value: 'notatedMusic', label: 'Noten' },
    { value: 'textTemplate', label: 'Textvorlage' },
    { value: 'drawing', label: 'Zeichnung' },
    { value: 'bill', label: 'Rechnung' },
    { value: 'print', label: 'Druckerzeugnis' },
    { value: 'diploma', label: 'Diplom' },
    { value: 'medal', label: 'Orden' },
    { value: 'other', label: 'Sonstiges' },
  ],
  noteTypeItems: [
    { value: 'these_comment', label: 'Themenkommentar' },
    { value: 'single_place_comment', label: 'Einzelstellenkommentar' },
    { value: 'text_constitution', label: 'Kommentar Textkonstitution' },
    { value: 'word_description', label: 'Worterklärung' },
  ],
  noteTypeLanguages: [
    { value: 'de', label: 'Deutsch' },
    { value: 'en', label: 'Englisch' },
    { value: 'fr', label: 'Französisch' },
    { value: 'it', label: 'Italienisch' },
    { value: 'span', label: 'Spanisch' },
    { value: 'la', label: 'Latein' },
    { value: 'grc', label: 'Altgriechisch' },
    { value: 'yi', label: 'Jiddisch' },
  ],
  menuItemTypes: {
    DELETE_NODE: 'DELETE_NODE',
    MANAGE_TEXT_ADDRESS: 'MANAGE_TEXT_ADDRESS',
    MANAGE_WRITER_AUTHOR_HEADER: 'MANAGE_WRITER_AUTHOR_HEADER',
    MANAGE_RECEIVER: 'MANAGE_RECEIVER',
    MANAGE_HEADER_LANGUAGES: 'MANAGE_HEADER_LANGUAGES',
    REMOVE_ANNOTATION: 'REMOVE_ANNOTATION',
    WRITING_ACT: {
      ADD_GREETINGS_FORMULA: 'ADD_GREETINGS_FORMULA',
      LABEL_MOVE_UP: 'LABEL_MOVE_UP',
      LABEL_MOVE_DOWN: 'LABEL_MOVE_DOWN',
      MOVE_UP: 'MOVE_UP',
      MOVE_DOWN: 'MOVE_DOWN',
      MANAGE_AUTHOR_WRITER: 'MANAGE_AUTHOR_WRITER',
      MANAGE_GREETINGS_FORMULA: 'MANAGE_GREETINGS_FORMULA',
      EDIT_NOTE: 'EDIT_NOTE',
    },
  },
  styles: {
    panel: {
      buttonSize: 'small',
    },
  },
  dateDialog: {
    dateTypes: {
      WHEN: 'when',
      WHEN_CUSTOM: 'when-custom',
      NOT_AFTER: 'notAfter',
      NOT_BEFORE: 'notBefore',
      FROM_TO: 'from-to',
      NOT_BEFORE_NOT_AFTER: 'notBefore-notAfter',
    },
  },
  camelCaseTags: [
    'accMat',
    'addName',
    'addrLine',
    'addSpan',
    'adminInfo',
    'altGrp',
    'altIdent',
    'altIdentifier',
    'annotationBlock',
    'anyElement',
    'appInfo',
    'attDef',
    'attList',
    'attRef',
    'biblFull',
    'biblScope',
    'biblStruct',
    'binaryObject',
    'bindingDesc',
    'calendarDesc',
    'castGroup',
    'castItem',
    'castList',
    'catDesc',
    'catRef',
    'charDecl',
    'charName',
    'charProp',
    'citeData',
    'citedRange',
    'citeStructure',
    'classCode',
    'classDecl',
    'classRef',
    'classSpec',
    'constraintSpec',
    'correspAction',
    'correspContext',
    'correspDesc',
    'cRefPattern',
    'custEvent',
    'custodialHist',
    'damageSpan',
    'dataFacet',
    'dataRef',
    'dataSpec',
    'decoDesc',
    'decoNote',
    'defaultVal',
    'delSpan',
    'dictScrap',
    'divGen',
    'docAuthor',
    'docDate',
    'docEdition',
    'docImprint',
    'docTitle',
    'editionStmt',
    'editorialDecl',
    'egXML',
    'eLeaf',
    'elementRef',
    'elementSpec',
    'encodingDesc',
    'entryFree',
    'eTree',
    'fDecl',
    'fDescr',
    'figDesc',
    'fileDesc',
    'finalRubric',
    'fLib',
    'floatingText',
    'fsConstraints',
    'fsdDecl',
    'fsDecl',
    'fsDescr',
    'fsdLink',
    'fvLib',
    'genName',
    'geoDecl',
    'geogFeat',
    'geogName',
    'glyphName',
    'gramGrp',
    'handDesc',
    'handNote',
    'handNotes',
    'handShift',
    'headItem',
    'headLabel',
    'iNode',
    'interpGrp',
    'iType',
    'joinGrp',
    'lacunaEnd',
    'lacunaStart',
    'langKnowledge',
    'langKnown',
    'langUsage',
    'layoutDesc',
    'linkGrp',
    'listAnnotation',
    'listApp',
    'listBibl',
    'listChange',
    'listEvent',
    'listForest',
    'listNym',
    'listObject',
    'listOrg',
    'listPerson',
    'listPlace',
    'listPrefixDef',
    'listRef',
    'listRelation',
    'listTranspose',
    'listWit',
    'localName',
    'localProp',
    'locusGrp',
    'macroRef',
    'macroSpec',
    'measureGrp',
    'memberOf',
    'metDecl',
    'metSym',
    'modelGrp',
    'modelSequence',
    'moduleRef',
    'moduleSpec',
    'msContents',
    'msDesc',
    'msFrag',
    'msIdentifier',
    'msItem',
    'msItemStruct',
    'msName',
    'msPart',
    'musicNotation',
    'nameLink',
    'notatedMusic',
    'noteGrp',
    'notesStmt',
    'objectDesc',
    'objectIdentifier',
    'objectName',
    'objectType',
    'oRef',
    'orgName',
    'origDate',
    'origPlace',
    'outputRendition',
    'paramList',
    'paramSpec',
    'particDesc',
    'persName',
    'personGrp',
    'persPronouns',
    'physDesc',
    'placeName',
    'postBox',
    'postCode',
    'pRef',
    'prefixDef',
    'profileDesc',
    'projectDesc',
    'publicationStmt',
    'pubPlace',
    'rdgGrp',
    'recordHist',
    'recordingStmt',
    'refsDecl',
    'refState',
    'relatedItem',
    'respStmt',
    'revisionDesc',
    'roleDesc',
    'roleName',
    'samplingDecl',
    'schemaRef',
    'schemaSpec',
    'scriptDesc',
    'scriptNote',
    'scriptStmt',
    'sealDesc',
    'secFol',
    'seriesStmt',
    'settingDesc',
    'soCalled',
    'socecStatus',
    'sourceDesc',
    'sourceDoc',
    'spanGrp',
    'specDesc',
    'specGrp',
    'specGrpRef',
    'specList',
    'spGrp',
    'standOff',
    'stdVals',
    'styleDefDecl',
    'substJoin',
    'superEntry',
    'supportDesc',
    'surfaceGrp',
    'tagsDecl',
    'tagUsage',
    'teiCorpus',
    'teiHeader',
    'textClass',
    'textDesc',
    'textLang',
    'textNode',
    'titlePage',
    'titlePart',
    'titleStmt',
    'transcriptionDesc',
    'typeDesc',
    'typeNote',
    'unicodeName',
    'unicodeProp',
    'unihanProp',
    'unitDecl',
    'unitDef',
    'valDesc',
    'valItem',
    'valList',
    'vAlt',
    'variantEncoding',
    'vColl',
    'vDefault',
    'vLabel',
    'vMerge',
    'vNot',
    'vRange',
    'witDetail',
    'witEnd',
    'witStart',
    'xenoData',
  ],
  TEI_NS: 'http://www.tei-c.org/ns/1.0',
} as const;
